### PR TITLE
chore: Port over wf4

### PR DESCRIPTION
**Pull request by patrickkenney9801**

### CODE REVIEW

**Comment by patrickkenney9801** [comment]
TODO: debug lfs issues

**Comment by AdityaAtulTewari** [comment]
is this ready for review?

**Comment by patrickkenney9801** [comment]
> is this ready for review?

yes

**Review by AdityaAtulTewari — APPROVED** [review]
Please make sure that wf4 test are off by default but turned on in the PREP pipeline in ci.

**Pull request merged**
