### PR TITLE
Small fix

### PR DESCRIPTION
**Pull request by AdityaAtulTewari**

### CODE REVIEW

**Review by jeageun — APPROVED** [review]
Looks good to me.

**Comment by jeageun** [comment]
When I check it locally, comment out include/pando-lib-galois/graph/mirror_dist_local_csr.hpp:324
//PANDO_CHECK(localMirrorToRemoteMasterOrderedTable.initialize());
Helps to resolve the issue... Do you think it is not necessary? I thought I added this line to ensure the correctness at some point...

**Comment by AdityaAtulTewari** [comment]
I'm curious what is causing that so I'm trying a few thing on my end but that insight is helpful.

**Comment by AdityaAtulTewari** [comment]
yeah the heap size was just too small, so I made it bigger

**Comment by AdityaAtulTewari** [comment]
This is still not fixing it, there is something wrong in drvx. Jeageun I'm going to have to revert the commit

**Comment by AdityaAtulTewari** [comment]
Commit had to be reverted instead.

**Pull request closed without merging**
